#!/bin/sh
case "$1" in
    start)
	/opt/mailwall/bin/forwarder.pl
	;;
    stop)
	kill `cat /var/run/forwarder.pid`
	;;
    restart)
	$0 stop
	$0 start
	;;
    *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
	;;
esac

exit 0

